name: Build jslang artifacts for all platforms

on:
    push:
        branches: [master]
    release:
        types: [created]

jobs:
    build-for-windows:
        name: Build jslang artifacts for Windows x64 platform
        runs-on: windows-2022
        permissions:
            contents: read
            packages: write

        steps:
            - uses: actions/checkout@v4

            - run: |
                pip install -r requirements.txt

            - name: Download latest slang release
              uses: robinraju/release-downloader@v1.11
              with:
                repository: shader-slang/slang
                latest: true
                fileName: slang-*-windows-x86_64.zip
                out-file-path: natives/slang.zip
                extract: true

            - name: (Powershell) Move automatically extracted natives/slang.zip/ to natives/slang/
              run: |
                Move-Item -Path natives/slang.zip -Destination natives/slang
                Get-ChildItem -Path natives/ -Recurse

            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: "temurin"
                  server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
                  settings-path: ${{ github.workspace }} # location for the settings.xml file

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@add58192d1c6f4603dc6821e8616f251e2782884 # maybe latest

            - name: Setup MSVC Dev Cmd
              uses: ilammy/msvc-dev-cmd@v1
              with:
                  arch: x64

            - name: (Powershell) Break cyclic dependency in Gradle tasks by temporarily move src/main/java/moyongxin/jslang/JSlang.java to .txt file
              run: Move-Item -Path src/main/java/moyongxin/jslang/JSlang.java -Destination src/main/java/moyongxin/jslang/JSlang.txt

            - name: Build with Gradle
              run: ./gradlew.bat build

            - name: Restore src/main/java/moyongxin/jslang/JSlang.java
              run: Move-Item -Path src/main/java/moyongxin/jslang/JSlang.txt -Destination src/main/java/moyongxin/jslang/JSlang.java

            - name: Build with Gradle again
              run: ./gradlew.bat build

            - name: (Powershell) Get project version from Gradle task printVersion which prints the version string like "0.0.1"
              id: get-version
              run: echo "::set-output name=version::$(./gradlew.bat printVersion -q)"

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4.4.3
              with:
                  name: jslang-${{ steps.get-version.outputs.version }}-windows-x64.jar
                  path: build/libs/jslang-${{ steps.get-version.outputs.version }}.jar
                  if-no-files-found: error
                  overwrite: true

            # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
            # the publishing section of your build.gradle
            # - name: Publish to GitHub Packages
            #   run: ./gradlew publish
            #   env:
            #       USERNAME: ${{ github.actor }}
            #       TOKEN: ${{ secrets.GITHUB_TOKEN }}

    build-for-linux:
        name: Build jslang artifacts for Linux platform
        runs-on: ubuntu-20.04
        permissions:
            contents: read
            packages: write

        steps:
            - uses: actions/checkout@v4

            - run: |
                sudo apt install ninja-build
                pip install -r requirements.txt

            - name: Download latest slang release
              uses: robinraju/release-downloader@v1.11
              with:
                repository: shader-slang/slang
                latest: true
                fileName: slang-*-linux-x86_64.zip
                out-file-path: natives/slang.zip
                extract: true

            - name: (Bash) Move automatically extracted natives/slang.zip/ to natives/slang/
              run: |
                mv natives/slang.zip natives/slang
                ls -R natives/

            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: "temurin"
                  server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
                  settings-path: ${{ github.workspace }} # location for the settings.xml file

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@add58192d1c6f4603dc6821e8616f251e2782884 # maybe latest

            - name: Setup ./gradlew permissions
              run: chmod +x gradlew

            - name: (Bash) Break cyclic dependency in Gradle tasks by temporarily move src/main/java/moyongxin/jslang/JSlang.java to .txt file
              run: mv src/main/java/moyongxin/jslang/JSlang.java src/main/java/moyongxin/jslang/JSlang.txt

            - name: Build with Gradle
              run: ./gradlew build

            - name: Restore src/main/java/moyongxin/jslang/JSlang.java
              run: mv src/main/java/moyongxin/jslang/JSlang.txt src/main/java/moyongxin/jslang/JSlang.java

            - name: Build with Gradle again
              run: ./gradlew build

            - name: Get project version from Gradle task printVersion which prints the version string like "0.0.1"
              id: get-version
              run: echo "::set-output name=version::$(./gradlew printVersion -q)"

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4.4.3
              with:
                  name: jslang-${{ steps.get-version.outputs.version }}-linux-x64.jar
                  path: build/libs/jslang-${{ steps.get-version.outputs.version }}.jar
                  if-no-files-found: error
                  overwrite: true

            # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
            # the publishing section of your build.gradle
            # - name: Publish to GitHub Packages
            #   run: ./gradlew publish
            #   env:
            #       USERNAME: ${{ github.actor }}
            #       TOKEN: ${{ secrets.GITHUB_TOKEN }}
