name: Build jslang artifacts for all platforms

on:
    push:
        branches: [master]
    release:
        types: [created]

jobs:
    build-for-windows:
        name: Build jslang artifacts for Windows x64 platform
        runs-on: windows-2022
        permissions:
            contents: read
            packages: write

        steps:
            - uses: actions/checkout@v4

            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: "temurin"
                  server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
                  settings-path: ${{ github.workspace }} # location for the settings.xml file

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@add58192d1c6f4603dc6821e8616f251e2782884 # maybe latest

            - name: Setup MSVC Dev Cmd
              uses: ilammy/msvc-dev-cmd@v1
              with:
                  arch: x64

            - name: Build with Gradle
              run: ./gradlew.bat build

            - name: Get project version from Gradle task printVersion which prints the version string like "0.0.1"
              id: get-version
              run: echo "::set-output name=version::$(./gradlew printVersion -q)"

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4.4.3
              with:
                  name: jslang-${{ steps.get-version.outputs.version }}-windows-x64.jar
                  path: build/libs/jslang-${{ steps.get-version.outputs.version }}.jar
                  if-no-files-found: error
                  overwrite: true

            # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
            # the publishing section of your build.gradle
            # - name: Publish to GitHub Packages
            #   run: ./gradlew publish
            #   env:
            #       USERNAME: ${{ github.actor }}
            #       TOKEN: ${{ secrets.GITHUB_TOKEN }}

    build-for-linux:
        name: Build jslang artifacts for Linux platform
        runs-on: ubuntu-20.04
        permissions:
            contents: read
            packages: write

        steps:
            - uses: actions/checkout@v4

            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: "temurin"
                  server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
                  settings-path: ${{ github.workspace }} # location for the settings.xml file

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@add58192d1c6f4603dc6821e8616f251e2782884 # maybe latest

            - name: Build with Gradle
              run: ./gradlew build

            - name: Get project version from Gradle task printVersion which prints the version string like "0.0.1"
              id: get-version
              run: echo "::set-output name=version::$(./gradlew printVersion -q)"

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4.4.3
              with:
                  name: jslang-${{ steps.get-version.outputs.version }}-linux-x64.jar
                  path: build/libs/jslang-${{ steps.get-version.outputs.version }}.jar
                  if-no-files-found: error
                  overwrite: true

            # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
            # the publishing section of your build.gradle
            # - name: Publish to GitHub Packages
            #   run: ./gradlew publish
            #   env:
            #       USERNAME: ${{ github.actor }}
            #       TOKEN: ${{ secrets.GITHUB_TOKEN }}
